"""Add tables

Revision ID: 2e56cf2b8c7b
Revises: 
Create Date: 2020-07-30 17:08:49.079304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e56cf2b8c7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jwks_url', sa.Text(), nullable=True),
    sa.Column('bound_issuer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jwt_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('bound_claims', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jwt_role')
    op.drop_table('jwt_config')
    # ### end Alembic commands ###
