"""add nomad claims

Revision ID: 3f70b745607b
Revises: 2e56cf2b8c7b
Create Date: 2020-07-31 19:14:55.424517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f70b745607b'
down_revision = '2e56cf2b8c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jwt_role', sa.Column('nomad_claims', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jwt_role', 'nomad_claims')
    # ### end Alembic commands ###
